package com.prc.domain;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.prc.user.AppUser;
import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.time.LocalDate;
import java.util.*;
import org.springframework.http.*;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.web.bind.annotation.*;

@RestController @RequestMapping("/api")
public class PlacementController {
 private final RoleProfileRepository roles; private final RoleSkillRepository skills; private final DiagnosticAttemptRepository diagnostics; private final LearningPlanItemRepository plans; private final InterviewLogRepository interviews; private final AuditEventRepository audit; private final ObjectMapper json;
 public PlacementController(RoleProfileRepository roles,RoleSkillRepository skills,DiagnosticAttemptRepository diagnostics,LearningPlanItemRepository plans,InterviewLogRepository interviews,AuditEventRepository audit,ObjectMapper json){this.roles=roles;this.skills=skills;this.diagnostics=diagnostics;this.plans=plans;this.interviews=interviews;this.audit=audit;this.json=json;}
 @GetMapping("/roles") public List<RoleView> roleProfiles(){return roles.findAll().stream().map(r->new RoleView(r.getId(),r.getName(),r.getSummary(),r.getIcon(),skills.findByRoleId(r.getId()).stream().map(s->new SkillView(s.getName(),s.getTarget())).toList())).toList();}
 @GetMapping("/me/dashboard") @PreAuthorize("hasRole('STUDENT')") public Dashboard dashboard(@AuthenticationPrincipal AppUser me){ var attempts=diagnostics.findByStudentOrderByCompletedAtDesc(me); var latest=attempts.isEmpty()?null:attempts.get(0); return new Dashboard(me.getName(),latest==null?null:latest.getRole().getId(),latest==null?0:latest.getScore(),latest==null?Map.of():readMap(latest.getTopicScoresJson()),plans.findByStudentOrderByTopic(me).stream().map(p->new PlanView(p.getId(),p.getTopic(),p.getTask(),p.isDone())).toList(),interviews.findByStudentOrderByInterviewDateDesc(me).stream().map(i->new InterviewView(i.getId(),i.getRoleName(),i.getInterviewDate(),i.getRating(),i.getNotes())).toList());}
 @PostMapping("/diagnostics") @PreAuthorize("hasRole('STUDENT')") public ResponseEntity<Void> submitDiagnostic(@AuthenticationPrincipal AppUser me,@Valid @RequestBody DiagnosticRequest r){RoleProfile role=roles.findById(r.roleId()).orElseThrow(()->new NoSuchElementException("Role profile not found")); if(r.topicScores().values().stream().anyMatch(n->n<0||n>100)) throw new IllegalArgumentException("Topic scores must be 0–100"); DiagnosticAttempt d=diagnostics.save(new DiagnosticAttempt(me,role,r.score(),writeMap(r.topicScores())));audit.save(new AuditEvent(me,"DIAGNOSTIC_SUBMITTED","DiagnosticAttempt",d.getId()));return ResponseEntity.status(HttpStatus.CREATED).build();}
 @PostMapping("/learning-plan") @PreAuthorize("hasRole('STUDENT')") public ResponseEntity<PlanView> addPlan(@AuthenticationPrincipal AppUser me,@Valid @RequestBody PlanRequest r){RoleProfile role=roles.findById(r.roleId()).orElseThrow(()->new NoSuchElementException("Role profile not found"));LearningPlanItem p=plans.save(new LearningPlanItem(me,role,r.topic(),r.task()));audit.save(new AuditEvent(me,"PLAN_ITEM_CREATED","LearningPlanItem",p.getId()));return ResponseEntity.status(HttpStatus.CREATED).body(new PlanView(p.getId(),p.getTopic(),p.getTask(),p.isDone()));}
 @PatchMapping("/learning-plan/{id}") @PreAuthorize("hasRole('STUDENT')") public PlanView updatePlan(@AuthenticationPrincipal AppUser me,@PathVariable String id,@Valid @RequestBody DoneRequest r){LearningPlanItem p=plans.findByIdAndStudent(id,me).orElseThrow(()->new NoSuchElementException("Plan item not found"));p.setDone(r.done());plans.save(p);audit.save(new AuditEvent(me,"PLAN_ITEM_UPDATED","LearningPlanItem",id));return new PlanView(p.getId(),p.getTopic(),p.getTask(),p.isDone());}
 @PostMapping("/interviews") @PreAuthorize("hasRole('STUDENT')") public ResponseEntity<InterviewView> addInterview(@AuthenticationPrincipal AppUser me,@Valid @RequestBody InterviewRequest r){InterviewLog i=interviews.save(new InterviewLog(me,r.role(),r.date(),r.rating(),r.notes()));audit.save(new AuditEvent(me,"INTERVIEW_LOGGED","InterviewLog",i.getId()));return ResponseEntity.status(HttpStatus.CREATED).body(new InterviewView(i.getId(),i.getRoleName(),i.getInterviewDate(),i.getRating(),i.getNotes()));}
 @GetMapping("/officer/readiness") @PreAuthorize("hasRole('PLACEMENT_OFFICER')") public OfficerSummary readiness(){var all=diagnostics.findAll();Map<String,List<DiagnosticAttempt>> groups=new TreeMap<>();all.forEach(d->groups.computeIfAbsent(d.getRole().getName(),k->new ArrayList<>()).add(d));return new OfficerSummary(all.size(),groups.entrySet().stream().map(e->new RoleReadiness(e.getKey(),e.getValue().size(),Math.round(e.getValue().stream().mapToInt(DiagnosticAttempt::getScore).average().orElse(0)*10)/10.0)).toList());}
 private Map<String,Integer> readMap(String raw){try{return json.readValue(raw,new TypeReference<>(){});}catch(Exception e){return Map.of();}} private String writeMap(Map<String,Integer> v){try{return json.writeValueAsString(v);}catch(Exception e){throw new IllegalArgumentException("Cannot encode scores");}}
 public record RoleView(String id,String name,String summary,String icon,List<SkillView> skills){} public record SkillView(String name,int target){} public record Dashboard(String name,String targetRoleId,int readiness,Map<String,Integer> topicScores,List<PlanView> learningPlan,List<InterviewView> interviews){} public record PlanView(String id,String topic,String task,boolean done){} public record InterviewView(String id,String role,LocalDate date,int rating,String notes){}
 public record DiagnosticRequest(@NotBlank String roleId,@Min(0) @Max(100) int score,@NotEmpty Map<@NotBlank String,@NotNull Integer> topicScores){} public record PlanRequest(@NotBlank String roleId,@NotBlank @Size(max=100) String topic,@NotBlank @Size(max=1000) String task){} public record DoneRequest(boolean done){} public record InterviewRequest(@NotBlank @Size(max=150) String role,@NotNull LocalDate date,@Min(1) @Max(5) int rating,@NotBlank @Size(max=2000) String notes){} public record OfficerSummary(int totalAttempts,List<RoleReadiness> roles){} public record RoleReadiness(String role,int assessedStudents,double averageScore){}
}
